### ISSUE TITLE
Wrong attribute to change index

### ISSUE THREAD

**Issue by rodfersou** [yhino/pipenv-poetry-migrate#48]
when have multiple sources, it's generating

```toml
package = {version = "*", index = "private_index"}
```

instead of:

```toml
package = {version = "*", source = "private_index"}
```

**Comment by yhino** [comment]
Thank you for the issue. I will fix it.

**Comment by yhino** [comment]
Sorry for the wait.

The version 0.3.2 is released.
https://pypi.org/project/pipenv-poetry-migrate/0.3.2/ 

Please try to use it.
