### ISSUE TITLE
Support option to re-migrate a dependency if it already exists in the poetry dependencies

### ISSUE THREAD

**Issue by pchrapka** [yhino/pipenv-poetry-migrate#62]
if a version constraint changes in the Pipfile, the pyproject.toml does not reflect the change

**Comment by yhino** [comment]
Thank you for your request.
I implemented it in [v0.5.0](https://pypi.org/project/pipenv-poetry-migrate/0.5.0/), does it match your request?

**Comment by pchrapka** [comment]
thanks @yhino !

**Comment by yhino** [comment]
You're welcome.
This issue is closed. If you find a problem, please re-open it.
